name: Pipeline API RESTful

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Login to Digital Ocean Registry
        run: echo "${{ secrets.DO_TOKEN }}" | docker login registry.digitalocean.com -u ${{ secrets.DO_TOKEN }} --password-stdin

      - name: Build and push Docker image to 'DO' Registry
        
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./src
          push: true
          tags: registry.digitalocean.com/registry-ntconsult-cr/api:v1
          build-args: |
            DB_CONNECTION_STRING="mongodb+srv://doadmin:Z2s369170Q8vMYNu@private-mongodb-ntconsult-tst-24287131.mongo.ondigitalocean.com/admin?tls=true&authSource=admin&replicaSet=mongodb-ntconsult-tst"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Set Kubeconfig
        uses: azure/k8s-set-context@v3
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy to Kubernetes
        run: |
          kubectl delete -f k8s/deployment.yaml
          kubectl delete -f k8s/loadbalancer.yaml
