on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Login to Digital Ocean Registry
        run: echo "${{ secrets.DO_TOKEN }}" | docker login registry.digitalocean.com -u ${{ secrets.DO_TOKEN }} --password-stdin

      - name: Print Working Directory
        run: pwd

      - name: Build and push Docker image to DO Registry
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./src
          push: true
          tags: registry.digitalocean.com/registry-ntconsult-cr/api:v1
          build-args: |
            DB_CONNECTION_STRING=${{ secrets.DB_CONNECTION_STRING }}
            
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set Kubeconfig
        uses: azure/k8s-set-context@v3
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          context: ./k8s
      
      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v4.0.0
        with:
          version: latest

      - name: Kubectl Apply
        run: kubectl apply -f namespace.yaml

