on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.2

      - name: Login to Digital Ocean Registry
        run: echo "${{ secrets.DO_TOKEN }}" | docker login registry.digitalocean.com -u ${{ secrets.DO_TOKEN }} --password-stdin

      - name: Build and push Docker image to DO Registry
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./src
          push: true
          tags: registry.digitalocean.com/registry-ntconsult-cr/api:v1
          build-args: |
            DB_CONNECTION_STRING=${{ secrets.DB_CONNECTION_STRING }}
            
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Kubernetes
        uses: Azure/k8s-deploy@v4.9
        with:
          manifests: ./k8s/namespace.yaml
          token: ${{ secrets.KUBECONFIG }}
